### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by kyota1210** [kyota1210/furima-30456#9]
#URL
https://furima-30456.herokuapp.com/

#Basic認証のIDとパスワード
ID : kyoro  ,  パスワード : 1210

#出品者用のメールアドレスとパスワード
メールアドレス : syuppin@syuppin.com
パスワード　　 : syuppin1

#購入者用のメールアドレスとパスワード
メールアドレス : kounyu@kounyu.com
パスワード　　 : kounyu2

#購入者カード情報
カード番号 : 4242424242424242
有効期限　 : 30 / 30
セキュリティコード : 123

**Comment by tec-camp** [comment]
kyota1210さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
○ クレジットカード決済ができる
→カード情報、及び、必須情報を入力しても決済を行うことができません。また、有効期限が30/30といただいておりますが、こちらは合っておりますでしょうか？

○ ログインしていないユーザーは購入ページに遷移しようとすると、ログインページに遷移する
→ログインしていない状態でトップページから購入ページのURL（https://furima-30456.herokuapp.com/items/61/orders ）
を直接入力すると下記画像に遷移します。ログインページに遷移するよう修正をお願いします。
<img width="592" alt="スクリーンショット 2020-10-13 10 57 59" src="https://user-images.githubusercontent.com/69298538/95806794-7f9e9000-0d43-11eb-930a-404ce901cd30.png">


修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by kyota1210** [comment]
挙動確認ありがとうございます！
修正しました。
クレジットカード有効期限、間違えてました。

#URL
https://furima-30456.herokuapp.com/

#Basic認証のIDとパスワード
ID : kyoro , パスワード : 1210

#出品者用のメールアドレスとパスワード
メールアドレス : syuppin@syuppin.com
パスワード　　 : syuppin1

#購入者用のメールアドレスとパスワード
メールアドレス : kounyu@kounyu.com
パスワード　　 : kounyu2

#購入者カード情報
カード番号 : 4242424242424242
有効期限　 : 3 / 30
セキュリティコード : 123

**Comment by tec-camp** [comment]
kyota1210さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
○ URLを直接入力して購入済み商品の購入ページへ遷移しようとすると、トップページに遷移する
→購入済み商品の購入ページURL（https://furima-30456.herokuapp.com/items/71/orders ) を入力すると、トップページではなく、購入済み商品画面に遷移します。修正をお願いします。

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by kyota1210** [comment]
挙動確認ありがとうございます！

商品購入機能の実装条件を確認してみたところ、
・ログイン・ログアウトの状態に関わらず、URLを直接入力して売却済み商品の商品購入ページへ遷移しようとすると、トップページに遷移すること
となっているのですが、トップページに遷移か購入済み商品画面に遷移かどちらが正しいでしょうか？

ご確認お願いいたします。

**Comment by tec-camp** [comment]
kyota1210 さん、ご提出ありがとうございます！
上記ですが先ほど挙動確認したところ、こちらの操作に誤りがあったのか、トップページではなく購入済み商品画面に遷移を確認しておりました。しかし、ただいま確認したところ問題なくトップページに遷移を確認させていただきました。お手数おかけいたしました。ご確認いただきありがとうございます。

全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
